In [10]:
from web_scraper import *
from feature_vectorizer import *

#Test to see if reducing the number of languages trained will improve results.
For this run will only train on the 17 languages being tested.

In [11]:
test_data = pd.read_pickle('train_for_17_languages.pkl')

In [12]:
test_data.shape

(11959, 2)

In [13]:
X_train = test_data[1]

In [14]:
y_train = test_data[0]

In [15]:
X_train.head()

10    def builtinsort(x):    x.sort() def partition(...
11    def ones(n):    return [1]*n def reversedrange...
12    def write_timings(npoints=10, maxN=10**4, sort...
13    import operatorimport numpy, pylabdef plotdd(d...
14    import collections, itertools, glob, reimport ...
Name: 1, dtype: object

In [16]:
y_train.head()

10    python
11    python
12    python
13    python
14    python
Name: 0, dtype: object

In [17]:
X_test = pd.read_pickle("test_X_values.pkl")

In [18]:
y_test = pd.read_pickle("test_y_values.pkl")

In [19]:
X_test = X_test.loc[:,0]

In [20]:
y_test = y_test.loc[:,1]

#Fit a Decision Tree and test

In [21]:
tree_pipe = make_pipe(DecisionTreeClassifier())

In [22]:
tree_pipe.fit(X_train, y_train)

Pipeline(steps=[('featureunion', FeatureUnion(n_jobs=1,
       transformer_list=[('countvectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
 ...min_samples_split=2, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best'))])

In [23]:
tree_pipe.score(X_test, y_test)

0.8125

In [24]:
print(classification_report(tree_pipe.predict(X_test), y_test))

             precision    recall  f1-score   support

       bash       0.00      0.00      0.00         1
    clojure       0.50      1.00      0.67         2
    haskell       0.67      0.67      0.67         3
       java       1.00      1.00      1.00         2
 javascript       0.75      1.00      0.86         3
       lisp       0.00      0.00      0.00         2
      ocaml       0.50      1.00      0.67         1
        php       0.67      1.00      0.80         2
     python       1.00      1.00      1.00         4
       ruby       1.00      1.00      1.00         3
      scala       1.00      0.50      0.67         4
     scheme       1.00      1.00      1.00         3
        tcl       1.00      1.00      1.00         2

avg / total       0.78      0.81      0.78        32



/Users/joshuahiggins/tiyd/homework/programming_language_classifier/programming-language-classifier/.direnv/python-3.4.3/lib/python3.4/site-packages/sklearn/metrics/classification.py:958: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [25]:
print(confusion_matrix(tree_pipe.predict(X_test), y_test))

[[0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 2]]


#Run a Random Forest with a reduced training set, only training for languages to be tested.

In [26]:
forest_pipe = make_pipe(RandomForestClassifier())

In [27]:
forest_pipe.fit(X_train, y_train)

Pipeline(steps=[('featureunion', FeatureUnion(n_jobs=1,
       transformer_list=[('countvectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
 ...n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False))])

In [28]:
forest_pipe.score(X_test, y_test)

0.90625

#Does much better with reduced training set.

In [29]:
print(classification_report(forest_pipe.predict(X_test), y_test))

             precision    recall  f1-score   support

    clojure       0.75      1.00      0.86         3
    haskell       1.00      1.00      1.00         3
       java       1.00      1.00      1.00         2
 javascript       1.00      1.00      1.00         4
      ocaml       1.00      1.00      1.00         2
        php       1.00      1.00      1.00         3
     python       1.00      0.67      0.80         6
       ruby       0.33      1.00      0.50         1
      scala       1.00      0.67      0.80         3
     scheme       1.00      1.00      1.00         3
        tcl       1.00      1.00      1.00         2

avg / total       0.96      0.91      0.91        32



In [30]:
print(confusion_matrix(forest_pipe.predict(X_test), y_test))

[[3 0 0 0 0 0 0 0 0 0 0]
 [0 3 0 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 0 0]
 [1 0 0 0 0 0 4 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 2 0 0]
 [0 0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0 0 2]]


#Will test on Bayes as well, but don't expect it to outperform random forest.

In [31]:
bayes_pipe = make_pipe(MultinomialNB())

In [32]:
bayes_pipe.fit(X_train, y_train)

Pipeline(steps=[('featureunion', FeatureUnion(n_jobs=1,
       transformer_list=[('countvectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
 ...ormer_weights=None)), ('multinomialnb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [33]:
bayes_pipe.score(X_test, y_test)

0.75

In [34]:
print(classification_report(bayes_pipe.predict(X_test), y_test))

             precision    recall  f1-score   support

        ada       0.00      0.00      0.00         1
    clojure       0.25      1.00      0.40         1
    haskell       1.00      1.00      1.00         3
       java       0.50      1.00      0.67         1
 javascript       0.75      1.00      0.86         3
       lisp       0.00      0.00      0.00         6
      ocaml       1.00      1.00      1.00         2
        php       0.33      1.00      0.50         1
     python       1.00      1.00      1.00         4
       ruby       1.00      1.00      1.00         3
      scala       1.00      1.00      1.00         2
     scheme       0.67      1.00      0.80         2
        tcl       1.00      0.67      0.80         3

avg / total       0.68      0.75      0.69        32



/Users/joshuahiggins/tiyd/homework/programming_language_classifier/programming-language-classifier/.direnv/python-3.4.3/lib/python3.4/site-packages/sklearn/metrics/classification.py:958: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [35]:
print(confusion_matrix(bayes_pipe.predict(X_test), y_test))

[[0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 3 0 0 1 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 2]]
