In [32]:
import pandas as pd
from web_scraper import *
from feature_vectorizer import *


#Testing with full data set on small test data set.

In [33]:
y_test = pd.read_pickle('test_y_values.pkl')

In [34]:
X_test = pd.read_pickle('test_X_values.pkl')

In [35]:
train = pd.read_pickle('700_scrape.pkl')

In [36]:
X_train = train[1]

In [37]:
y_train = train[0]

In [38]:
pipe = make_pipe(RandomForestClassifier())

In [39]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('featureunion', FeatureUnion(n_jobs=1,
       transformer_list=[('countvectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
 ...n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False))])

In [40]:
X_test = X_test[0]

In [41]:
y_test = y_test[1]

In [42]:
pipe.score(X_test, y_test)

0.8125

##Does pretty well, may do better if we reduce the number of languages trained.  Now we are training on languages that will not be tested.

In [43]:
from sklearn.metrics import classification_report, confusion_matrix


In [44]:
print(classification_report(pipe.predict(X_test), y_test))

             precision    recall  f1-score   support

        ada       0.00      0.00      0.00         1
          c       0.00      0.00      0.00         1
    clojure       1.00      1.00      1.00         4
        cpp       0.00      0.00      0.00         2
    haskell       0.67      1.00      0.80         2
          j       0.00      0.00      0.00         1
       java       0.00      0.00      0.00         1
 javascript       1.00      1.00      1.00         4
      ocaml       1.00      1.00      1.00         2
        php       0.33      1.00      0.50         1
     python       1.00      1.00      1.00         4
       ruby       0.67      1.00      0.80         2
      scala       1.00      1.00      1.00         2
     scheme       1.00      1.00      1.00         3
        tcl       1.00      1.00      1.00         2

avg / total       0.75      0.81      0.77        32



/Users/joshuahiggins/tiyd/homework/programming_language_classifier/programming-language-classifier/.direnv/python-3.4.3/lib/python3.4/site-packages/sklearn/metrics/classification.py:958: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [45]:
print(confusion_matrix(pipe.predict(X_test), y_test))

[[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 4 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 4 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2]]


#Train on MultinomialNB

In [46]:
nb_pipe = make_pipe(MultinomialNB())

In [47]:
nb_pipe.fit(X_train, y_train)

Pipeline(steps=[('featureunion', FeatureUnion(n_jobs=1,
       transformer_list=[('countvectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
 ...ormer_weights=None)), ('multinomialnb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [48]:
nb_pipe.score(X_test, y_test)

0.5625

#Train with Decision Tree

In [49]:
tree_pipe = make_pipe(DecisionTreeClassifier())

In [50]:
tree_pipe.fit(X_train, y_train)

Pipeline(steps=[('featureunion', FeatureUnion(n_jobs=1,
       transformer_list=[('countvectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
 ...min_samples_split=2, min_weight_fraction_leaf=0.0,
            random_state=None, splitter='best'))])

In [51]:
tree_pipe.score(X_test, y_test)

0.65625

In [52]:
print(classification_report(tree_pipe.predict(X_test), y_test))

             precision    recall  f1-score   support

 autohotkey       0.00      0.00      0.00         1
       bash       0.00      0.00      0.00         1
    clojure       0.50      1.00      0.67         2
          d       0.00      0.00      0.00         1
    haskell       0.33      0.50      0.40         2
       java       1.00      1.00      1.00         2
 javascript       0.75      1.00      0.86         3
       lisp       0.00      0.00      0.00         2
      ocaml       1.00      1.00      1.00         2
         oz       0.00      0.00      0.00         1
     parigp       0.00      0.00      0.00         1
        php       0.33      1.00      0.50         1
  purebasic       0.00      0.00      0.00         1
     python       0.75      0.75      0.75         4
       ruby       1.00      0.75      0.86         4
      scala       0.50      1.00      0.67         1
     scheme       0.33      1.00      0.50         1
        tcl       1.00      1.00      1.00   

/Users/joshuahiggins/tiyd/homework/programming_language_classifier/programming-language-classifier/.direnv/python-3.4.3/lib/python3.4/site-packages/sklearn/metrics/classification.py:958: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
