In [783]:
import pandas as pd

import re
import os
import nltk

In [707]:
topdir ='/Users/keithcalise/Github/programming-language-classifier/benchmarksgame-2014-08-31/benchmarksgame/bench/'
testdir = '/Users/keithcalise/GitHub/programming-language-classifier/test/'
file_extensions = {".clj":"Clojure",
                 ".cljs": "Clojure",
                 ".clojure": "Clojure",
                 ".hs": "Haskell",
                 ".lhs": "Haskell",
                 ".java": "Java",
                 ".class": "Java",
                 ".jar": "Java",
                 ".js": "Javascript",
                 ".javascript": "Javascript",
                 ".pl": "Perl",
                 ".pm": "Perl",
                 ".t": "Perl",
                 ".pod": "Perl",
                 ".php": "PHP",
                 ".php4": "PHP",
                 ".perl": "Perl",
                 ".phtml": "PHP",
                 ".py": "Python",
                 ".pyw": "Python",
                 ".pyc": "Python",
                 ".pyo": "Python",
                 ".pyd": "Python",
                 ".python3": "Python",
                 ".Python2": "Python",
                 ".rb": "Ruby",
                 ".rbw": "Ruby",
                 ".jruby": "Ruby",
                 ".scala": "Scala",
                 ".scm": "Scheme",
                 ".ss": "Scheme",
                 ".tcl": "Tcl",
                 ".racket": "Scheme",
                 ".ghc": "Haskell",
                 ".Tcl": "Tool Command Language"}


def tupler(dic):
    keylist = []
    for key in dic:
        keylist.append(key)
    tupl = tuple(keylist)
    return tupl


def get_files_dirs(directory):
    data = []
    for dirpath, dirnames, names in os.walk(topdir):
        for name in names:
            if name.lower().endswith(tupler(file_extensions)):
                with open(os.path.join(dirpath,name)) as current_file:
                    data.append(current_file.read())

    return data  


def code_getter(directory):
    
    typelist = []
    for dirpath, dirnames, names in os.walk(topdir):
        for file_name in names:
            name, extension = os.path.splitext(file_name)
            if extension in file_extensions:
#                 print(file_extensions[extension])
                typelist.append(file_extensions[extension])
    return typelist

In [708]:
def count_char(code, char):
    counter = 0
    for i in code:
        if i == char:
            counter+=1
    return counter
def char_centage(code, char):
    num = count_char(code, char)/len(code)
    return num
def stringer(code, string):
    num = len(re.findall(string, code))
    return num
def string_centage(code,string):
    num = stringer(code, string)/len(code)
    return num
# string_centage(df.Code[3],'check')
# count_char(df.Code[3],"-")
# char_centage(df.Code[3],"-")

In [709]:

string_centage(df.loc[20]['Code'], 'elif')

0.0

In [710]:
def df_maker(directory):
    filename_list = get_files_dirs(directory)
    typelist = code_getter(directory)
    df = pd.DataFrame(typelist, index = range(352))
    df.columns = ["Language"]
    df['Code']=filename_list
    df["Language"]=df.Language.apply(lambda x:x.lower())
    df['Code Length']=df.Code.apply(lambda x:len(x))
    return df
df = df_maker(topdir)

In [711]:

char_centage(df['Code'][0],"^")

0.00371900826446281

In [712]:
def carat(code):
    return char_centage(code, '^')*100
    
def ampersand(code):
    return char_centage(code,"&")*100
    
def double_equals(code):
    return char_centage(code, '==')*100

def semicolon(code):
    return char_centage(code,';')*100
def exclamation(code):
    return char_centage(code, '!')*100
def comma(code):
    return char_centage(code,',')*100
def colon(code):
    return char_centage(code,':')*100
def pipe(code):
    return char_centage(code,'|')*100

def elif_(code):
    return string_centage(code, 'elif')*100
def if_(code):
    return string_centage(code, 'if')*100
def return_(code):
    return string_centage(code, 'return')*100
def println(code):
    return string_centage(code,'println')*100
def open_curly(code):
    return char_centage(code, '{')*100
def end(code):
    return string_centage(code,'end')*100
def require(code):
    return string_centage(code,'require')*100
def void(code):
    return string_centage(code,'void')*100
# def column_generator(dataframe):
#     punc_list = ['^',':',',','$','|','!','&']
#     for punc in punc_list:
#         for code in df.Code:
#             code = code.split()
#             dataframe[punc]=dataframe.Code.apply(char_centage(code, punc))
#     return dataframe
# column_generator(df)
    
   

In [713]:
df['^'] = df.Code.apply(carat)
df['&'] = df.Code.apply(ampersand)
df['=='] = df.Code.apply(double_equals)
df[';'] = df.Code.apply(semicolon)
df[':'] = df.Code.apply(colon)
df[','] = df.Code.apply(comma)
df['!'] = df.Code.apply(exclamation)
df['|'] = df.Code.apply(pipe)
df['elif'] = df.Code.apply(elif_)
df['if'] = df.Code.apply(if_)
df['return'] = df.Code.apply(return_)
df['println'] = df.Code.apply(println)
df['{'] = df.Code.apply(open_curly)
df['end']=df.Code.apply(end)
df['require'] = df.Code.apply(require)
df['void']=df.Code.apply(void)

In [714]:
tester= pd.read_csv('test.csv', header=None)

In [715]:
def test_code_getter(directory):
    test_list = []
    for subdir, dirs, files in os.walk(directory):
        for filname in files:
            with open(os.path.join(subdir, filname)) as current_file:
                test_list.append(current_file.read())
    return test_list

In [716]:
test_code_list = test_code_getter(testdir)

In [717]:
tester['Tester_code'] = test_code_list

In [718]:
tester["Code Length"]= tester.Tester_code.apply(lambda x:len(x))

In [719]:
tester['^'] = df.Code.apply(carat)
tester['&'] = df.Code.apply(ampersand)
tester['=='] = df.Code.apply(double_equals)
tester[';'] = df.Code.apply(semicolon)
tester[':'] = df.Code.apply(colon)
tester[','] = df.Code.apply(comma)
tester['!'] = df.Code.apply(exclamation)
tester['|'] = df.Code.apply(pipe)
tester['elif'] = df.Code.apply(elif_)
tester['if'] = df.Code.apply(if_)
tester['return'] = df.Code.apply(return_)
tester['println'] = df.Code.apply(println)
tester['{'] = df.Code.apply(open_curly)
tester['end']=df.Code.apply(end)
tester['require'] = df.Code.apply(require)
tester['void'] = df.Code.apply(void)

In [720]:
tester = tester.rename(columns = {1:'Language'},)

Finally ready for sci-kit learn...


In [765]:
import sklearn.tree
import numpy as np
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB 

In [766]:
# X_train = df.loc[:,"^":]
# X_test = tester.loc[:,'^':]
# y_train = df.Language
# y_test = tester.Language


In [775]:
X_train, X_test, y_train, y_test = train_test_split(df.loc[:,'^':], df.Language, test_size=0.40)

In [776]:
tree = sklearn.tree.DecisionTreeClassifier()
tree = tree.fit(X_train, y_train)


In [777]:
print(metrics.classification_report(y_test, tree.predict(X_test)))
print(metrics.confusion_matrix(y_test, tree.predict(X_test)))

             precision    recall  f1-score   support

    clojure       0.85      0.69      0.76        16
    haskell       1.00      0.79      0.88        14
       java       0.93      1.00      0.96        25
 javascript       0.36      0.45      0.40        11
       perl       0.36      0.36      0.36        11
        php       0.54      0.58      0.56        12
     python       0.79      1.00      0.88        11
       ruby       0.94      0.79      0.86        19
      scala       0.71      0.77      0.74        13
     scheme       0.88      0.78      0.82         9

avg / total       0.77      0.75      0.76       141

[[11  0  1  1  0  3  0  0  0  0]
 [ 0 11  0  0  0  0  3  0  0  0]
 [ 0  0 25  0  0  0  0  0  0  0]
 [ 0  0  0  5  4  1  0  0  0  1]
 [ 0  0  1  4  4  2  0  0  0  0]
 [ 0  0  0  2  3  7  0  0  0  0]
 [ 0  0  0  0  0  0 11  0  0  0]
 [ 0  0  0  0  0  0  0 15  4  0]
 [ 0  0  0  2  0  0  0  1 10  0]
 [ 2  0  0  0  0  0  0  0  0  7]]


In [778]:
tree.score(X_train,y_train)

1.0

MultinomialNB

In [779]:
nb=MultinomialNB()

In [780]:
nb.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [781]:
nb.score(X_test, y_test)

0.67375886524822692

In [782]:
print(metrics.classification_report(y_test,nb.predict(X_test)))

             precision    recall  f1-score   support

    clojure       0.80      0.75      0.77        16
    haskell       0.91      0.71      0.80        14
       java       0.60      1.00      0.75        25
 javascript       0.00      0.00      0.00        11
       perl       0.29      0.45      0.36        11
        php       0.00      0.00      0.00        12
     python       0.71      0.91      0.80        11
       ruby       0.88      0.79      0.83        19
      scala       0.67      0.92      0.77        13
     scheme       0.86      0.67      0.75         9

avg / total       0.60      0.67      0.62       141



/Users/keithcalise/GitHub/programming-language-classifier/.direnv/python-3.4.3/lib/python3.4/site-packages/sklearn/metrics/classification.py:958: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
